### ISSUE TITLE
out of memory error.

### ISSUE THREAD

**Issue by madhavanmalolan** [jujojujo2003/AnDCpp#1]
Stack Trace:

11-01 14:54:35.981: E/AndroidRuntime(26855): FATAL EXCEPTION: Thread-3328
11-01 14:54:35.981: E/AndroidRuntime(26855): java.lang.OutOfMemoryError: [memory exhausted]
11-01 14:54:35.981: E/AndroidRuntime(26855):    at dalvik.system.NativeStart.main(Native Method)

This happens when downloading LARGE sharer's filelist, like "HumanValues-Main"

**Comment by phinfinity** [comment]
Ummm we can't really help it right now. We are using a really inefficient
xml parser which uses twice as much memory as the file list. I could try
reducing this by half, but reducing it even more will be really hard.

**Comment by jujojujo2003** [comment]
Anish r u using a DOM XML parser? Why didnt u use a streaming parser?

**Comment by phinfinity** [comment]
yes, because I was lazy :P , That is what I mentioned above. using SAX parser can bring down memory usage by half. It's a bit of effort though not straightforward trivial

**Comment by phinfinity** [comment]
This is a bug with libjdcpp , closing this and opening issue there.
