### ISSUE TITLE
Illegal State Exception

### ISSUE THREAD

**Issue by madhavanmalolan** [jujojujo2003/AnDCpp#14]
Have not been able to recreate the bug, will update here if i know of it.

02-25 17:30:28.445: E/AndroidRuntime(10007): FATAL EXCEPTION: main
02-25 17:30:28.445: E/AndroidRuntime(10007): java.lang.IllegalStateException: Can't change tag of fragment FileListFragment{42ec5538 #3 id=0x7f08000a android:switcher:2131230730:3}: was android:switcher:2131230730:3 now android:switcher:2131230730:4
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:398)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.app.BackStackRecord.add(BackStackRecord.java:389)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:99)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:832)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.view.ViewPager.populate(ViewPager.java:1048)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:550)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:509)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:908)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2805)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at com.phinmadvader.andcpp.TabPagerAdapter.add_tab(TabPagerAdapter.java:61)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at com.phinmadvader.andcpp.MainActivity.onQueryTextSubmit(MainActivity.java:208)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.widget.SearchView.onSubmitQuery(SearchView.java:1203)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.widget.SearchView.access$900(SearchView.java:93)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.widget.SearchView$8.onEditorAction(SearchView.java:1178)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.widget.TextView.onEditorAction(TextView.java:4973)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:297)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.os.Looper.loop(Looper.java:176)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at android.app.ActivityThread.main(ActivityThread.java:5419)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at java.lang.reflect.Method.invokeNative(Native Method)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at java.lang.reflect.Method.invoke(Method.java:525)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
02-25 17:30:28.445: E/AndroidRuntime(10007):    at dalvik.system.NativeStart.main(Native Method)

**Comment by phinfinity** [comment]
Fixed as of 97ef6df4b3a.
Did away with nested fragments completely, to avoid this issue. But as a result have compromised on performance by disabling some aspects of caching. Should try to address in a future commit to improve performance.
