### ISSUE TITLE
File-List viewing showes size in bytes

### ISSUE THREAD

**Issue by phinfinity** [jujojujo2003/AnDCpp#2]
Right now when viewing a given user's file-list the directory/file sizes are given in large 10+ digit bytes which is un-readable. prefer to auto-parse this as kb,mb,gb,tb.
(This is up for grabs, claim issue before implementing so that someone else doesn't double work))

**Comment by madhavanmalolan** [comment]
Added. 
Push id : 66cea549e1796d1b2991f610c994f303eaf2c80c
